/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as ApiPublicChatPhotoRouteImport } from './routes/api/public/chat-photo'
import { Route as ApiPublicCronRemindersRouteImport } from './routes/api/public/cron/reminders'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatPhotoRoute = ApiPublicChatPhotoRouteImport.update({
  id: '/api/public/chat-photo',
  path: '/api/public/chat-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRemindersRoute = ApiPublicCronRemindersRouteImport.update({
  id: '/api/public/cron/reminders',
  path: '/api/public/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/payouts': typeof PayoutsRoute
  '/api/public/chat-photo': typeof ApiPublicChatPhotoRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/payouts': typeof PayoutsRoute
  '/api/public/chat-photo': typeof ApiPublicChatPhotoRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/payouts': typeof PayoutsRoute
  '/api/public/chat-photo': typeof ApiPublicChatPhotoRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/payouts'
    | '/api/public/chat-photo'
    | '/api/public/cron/reminders'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/payouts'
    | '/api/public/chat-photo'
    | '/api/public/cron/reminders'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/payouts'
    | '/api/public/chat-photo'
    | '/api/public/cron/reminders'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PayoutsRoute: typeof PayoutsRoute
  ApiPublicChatPhotoRoute: typeof ApiPublicChatPhotoRoute
  ApiPublicCronRemindersRoute: typeof ApiPublicCronRemindersRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat-photo': {
      id: '/api/public/chat-photo'
      path: '/api/public/chat-photo'
      fullPath: '/api/public/chat-photo'
      preLoaderRoute: typeof ApiPublicChatPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/reminders': {
      id: '/api/public/cron/reminders'
      path: '/api/public/cron/reminders'
      fullPath: '/api/public/cron/reminders'
      preLoaderRoute: typeof ApiPublicCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PayoutsRoute: PayoutsRoute,
  ApiPublicChatPhotoRoute: ApiPublicChatPhotoRoute,
  ApiPublicCronRemindersRoute: ApiPublicCronRemindersRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
